version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/socket_BE
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root